### SolBeePop ####################################################
### Calibration and validation
### Script for SolBeePop setup and runs (NetLogo BehaviorSpace runs from batch) 
### Author: Amelie Schmolke / Colleen Roy
### Date: December 2022
###################################################################

rm(list = ls()) # clean up workspace
library(XML) # load library

## Commands in CommandPrompt to run the .bat file generated by this script:
# cd C:\Program Files\NetLogo 6.2.0\app
# [ofp]\run.bat

## Inputs ---------------------------------------------------------------------
ofp = 'C:\\SolBeePop\\Calibration_Validation\\Validation'  # output file path
mfp = 'D:\\SolBeePop\\SolBeePop.nlogo'
sim_set_name = 'run_S15_01802_validation'

## Set Up ---------------------------------------------------------------------
setwd(ofp)
vdf = read.csv(paste0(sim_set_name,'.csv'), stringsAsFactors = FALSE, check.names = FALSE)
vls = c(  # numeric inputs to NetLogo
  'Start.day', 'Initial.num.f', 'Initial.num.m', 'Initial.age', 'RndSeed',
  'Num.repeat.yr', 'DD.thresh.s', 'DD.max.cells.s', 'DD.log.slope',
  'day.emerge.f', 'var.emerge.f', 'day.emerge.m',
  'var.emerge.m', 'latest.emerge', 'dev.egg', 'dev.larva', 'dev.cocoon',
  't.maturation', 'm.life', 'max.nesting.life', 'p.max.nesting.life',
  'max.f.ratio', 'max.cells', 'max.survival.e.f', 'max.survival.e.m',
  'emerged.survival', 'a.cell.age', 'a.sex.age', 'a.size.age',
  'a.cell.resource', 'a.sex.resource', 'a.size.resource')
ols = c('doy', 'year', 'DateREP', 'count turtles', 'bees.emerged.yr',
  'f.emerged.yr', 'm.emerged.yr', 'bees.nesting', 'bees.nesting.today',
  'sum.cells.today', 'sum.f.cells.today', 'sum.m.cells.today', 'sum.cells',
  'sum.f.cells', 'sum.m.cells', 'mean.cells.today', 'mean.f.cells.today',
  'mean.m.cells.today', 'mean.cells', 'mean.f.cells', 'mean.m.cells')

## Create xml and bat files ---------------------------------------------------
bls = c()

xls = xmlHashTree() 
nde = addNode(xmlNode('experiments'), character(), xls)

# Loop through scenarios
for(i in 1:nrow(vdf)){
  ## assign variable values
  for(j in colnames(vdf)){
    x = vdf[i,j]
    if(grepl(',', x)) x = trimws(strsplit(x, ',')[[1]])  # split list
    if(j %in% vls) x = as.numeric(x)  # format number
    assign(j, x)
    rm(x)
  }
  rm(j)
  
  ## Add to bat file
  bls = c(bls, 
    paste('java -Xmx8000m -Dfile.encoding=UTF-8 -cp netlogo-6.2.0.jar', 
      'org.nlogo.headless.Main --model', mfp,
      '--setup-file', paste0(ofp, paste0('\\',sim_set_name,'.xml')),
      '--experiment', i,
      '--table', paste0(ofp, '\\', name, '.csv')))

  ## Add to xml file
  snde = addNode(xmlNode('experiment',  # scenario name
    attrs = c(name = i, repetitions = '1', 
      runMetricsEveryStep = 'true')), nde, xls)
  tnde = addNode(xmlNode('setup'), snde, xls)  # set up
  addNode(xmlTextNode('setup'), tnde, xls)
  tnde = addNode(xmlNode('go'), snde, xls)  # go
  addNode(xmlTextNode('go'), tnde, xls)
  # addNode(xmlNode('timeLimit', attrs = c(steps = 365*2)), snde, xls)  # steps
  for(j in ols){
    tnde = addNode(xmlNode('metric'), snde, xls)
    addNode(xmlTextNode(j), tnde, xls)
  }
  rm(j)

  for(j in colnames(vdf)){  # input values
    if(j == 'name') next
    tnde = addNode(xmlNode('enumeratedValueSet', 
      attrs = c(variable = j)), snde, xls)
    for(k in get(j)) {
      if(class(k) == 'character' | is.na(k)){
        k = paste0('\"', k, '\"')
      } else if(class(k) == 'logical'){
        k =  tolower(k)
      }
      addNode(xmlNode('value', attrs = c(value = k)), tnde, xls)
    }
    rm(k)
  }
  rm(j)
}

# write xml file
write('<?xml version="1.0" encoding="UTF-8"?>', file = paste0(sim_set_name,'.xml'))
write('<!DOCTYPE experiments SYSTEM "behaviorspace.dtd">',
  file = paste0(sim_set_name,'.xml'), append = TRUE)
capture.output(xls, file = paste0(sim_set_name,'.xml'), append = TRUE)

writeLines(bls, paste0(sim_set_name,'.bat'))  # write bat file

rm(list = ls()) # clean up workspace
