## SolBeePop_ecotox: landscape application
## Simulation of Ruddle et al. (2018) field studies
## Script for plotting simulation outputs along with study data 
## Manuscript Fig. 2: Combine into a 6-panel figure: plots from all 6 study locations (Ruddle et al. 2018) and corresponding simulations
## Individual plots are generated by the script Plot_field_sims_funct.R
## Author: Amelie Schmolke

Sys.setlocale("LC_ALL", "English") # to make sure dates appear in English in plots

### Note: 
##    SceA = sce (a) = low detail scenario
##    SceB = sce (b) = medium detail scenario
##    SceC = sce (c) = high detail scenario

setwd("C:/SolBeePop/Field_study_simulations/")

# specifications of study data and simulation outputs to plot
specs <- data.frame(run_num = c("Kra2014_SceC_1200m_dist_IT","Tue2014_SceC_1200m_dist_IT","For2014_SceC_1200m_dist_IT",
                                "Nie2015_SceC_1200m_dist_IT","Tue2015_SceC_1200m_dist_IT","Cel2015_SceC_1200m_dist_IT"),
                    studyID = c("S14-01501","S14-01570","S14-01571","S15-01802","S15-01803","S15-01804"),
                    plot_title = c("Kraichtal 2014", "Tübingen 2014", "Fortschwihr 2014", 
                                   "Niefern 2015", "Tübingen 2015", "Celle 2015"),
                    study_year = c(2014,2014,2014,2015,2015,2015))

# prepare ggplots for each study data / simulation output combination
plot_list <- list()
for(tt in 1:length(specs$run_num)){
  run_num <- specs$run_num[tt]
  studyID <- specs$studyID[tt]
  plot_title <- specs$plot_title[tt]
  study_year <- specs$study_year[tt]
  xlabel <- 0
  ylabel <- 1
  if(tt == 3){xlabel <- 1}
  if(tt == 6){xlabel <- 1}
  if(tt > 3){ylabel <- 0}
  source("C:/SolBeePop/Scripts/Plot_field_sims_funct.R")
  plot_list[[tt]] <- study_brood
}

# arrange the plots in two columns and three rows (2014 trials on the left, 2015 on the right)
# plots are all the same size
# axis titles only included in the left column for the y-axis and the bottom row for the x-axis
p_brood1 <- ggplotGrob(plot_list[[1]])
p_brood2 <- ggplotGrob(plot_list[[2]])
p_brood3 <- ggplotGrob(plot_list[[3]])
p_brood4 <- ggplotGrob(plot_list[[4]])
p_brood5 <- ggplotGrob(plot_list[[5]])
p_brood6 <- ggplotGrob(plot_list[[6]])
combi1 <- rbind(p_brood1,p_brood2,p_brood3, size = "last")
combi2 <- rbind(p_brood4,p_brood5,p_brood6, size = "last")
combi <- cbind(combi1, combi2)
ggsave("Fig2_field_sims_all_SceC.jpg",combi, dpi=300, width = 11, height = 14)
